// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.sonymobile.wozard.puppet.messages;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string cmd = 2;
    boolean hasCmd();
    String getCmd();

    // optional .messages.Data data = 4;
    boolean hasData();
    com.sonymobile.wozard.puppet.messages.Protocol.Data getData();
    com.sonymobile.wozard.puppet.messages.Protocol.DataOrBuilder getDataOrBuilder();

    // optional string req = 5;
    boolean hasReq();
    String getReq();

    // optional string info = 6;
    boolean hasInfo();
    String getInfo();

    // optional .messages.Location loc = 7;
    boolean hasLoc();
    com.sonymobile.wozard.puppet.messages.Protocol.Location getLoc();
    com.sonymobile.wozard.puppet.messages.Protocol.LocationOrBuilder getLocOrBuilder();

    // optional bytes screen = 1;
    boolean hasScreen();
    com.google.protobuf.ByteString getScreen();

    // optional uint32 ping = 8;
    boolean hasPing();
    int getPing();

    // optional bytes cam = 9;
    boolean hasCam();
    com.google.protobuf.ByteString getCam();

    // optional string speech = 10;
    boolean hasSpeech();
    String getSpeech();

    // optional string voicecommand = 11;
    boolean hasVoicecommand();
    String getVoicecommand();
  }
  public static final class Base extends
      com.google.protobuf.GeneratedMessage
      implements BaseOrBuilder {
    // Use Base.newBuilder() to construct.
    private Base(Builder builder) {
      super(builder);
    }
    private Base(boolean noInit) {}

    private static final Base defaultInstance;
    public static Base getDefaultInstance() {
      return defaultInstance;
    }

    public Base getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sonymobile.wozard.puppet.messages.Protocol.internal_static_messages_Base_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sonymobile.wozard.puppet.messages.Protocol.internal_static_messages_Base_fieldAccessorTable;
    }

    private int bitField0_;
    // optional string cmd = 2;
    public static final int CMD_FIELD_NUMBER = 2;
    private java.lang.Object cmd_;
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          cmd_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .messages.Data data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private com.sonymobile.wozard.puppet.messages.Protocol.Data data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.sonymobile.wozard.puppet.messages.Protocol.Data getData() {
      return data_;
    }
    public com.sonymobile.wozard.puppet.messages.Protocol.DataOrBuilder getDataOrBuilder() {
      return data_;
    }

    // optional string req = 5;
    public static final int REQ_FIELD_NUMBER = 5;
    private java.lang.Object req_;
    public boolean hasReq() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getReq() {
      java.lang.Object ref = req_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          req_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getReqBytes() {
      java.lang.Object ref = req_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        req_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string info = 6;
    public static final int INFO_FIELD_NUMBER = 6;
    private java.lang.Object info_;
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getInfo() {
      java.lang.Object ref = info_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          info_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .messages.Location loc = 7;
    public static final int LOC_FIELD_NUMBER = 7;
    private com.sonymobile.wozard.puppet.messages.Protocol.Location loc_;
    public boolean hasLoc() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.sonymobile.wozard.puppet.messages.Protocol.Location getLoc() {
      return loc_;
    }
    public com.sonymobile.wozard.puppet.messages.Protocol.LocationOrBuilder getLocOrBuilder() {
      return loc_;
    }

    // optional bytes screen = 1;
    public static final int SCREEN_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString screen_;
    public boolean hasScreen() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.google.protobuf.ByteString getScreen() {
      return screen_;
    }

    // optional uint32 ping = 8;
    public static final int PING_FIELD_NUMBER = 8;
    private int ping_;
    public boolean hasPing() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getPing() {
      return ping_;
    }

    // optional bytes cam = 9;
    public static final int CAM_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString cam_;
    public boolean hasCam() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.google.protobuf.ByteString getCam() {
      return cam_;
    }

    // optional string speech = 10;
    public static final int SPEECH_FIELD_NUMBER = 10;
    private java.lang.Object speech_;
    public boolean hasSpeech() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getSpeech() {
      java.lang.Object ref = speech_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          speech_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSpeechBytes() {
      java.lang.Object ref = speech_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        speech_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    // optional string voicecommand = 11;
    public static final int VOICECOMMAND_FIELD_NUMBER = 11;
    private java.lang.Object voicecommand_;
    public boolean hasVoicecommand() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getVoicecommand() {
      java.lang.Object ref = voicecommand_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          voicecommand_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getVoicecommandBytes() {
      java.lang.Object ref = voicecommand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        voicecommand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    private void initFields() {
      cmd_ = "";
      data_ = com.sonymobile.wozard.puppet.messages.Protocol.Data.getDefaultInstance();
      req_ = "";
      info_ = "";
      loc_ = com.sonymobile.wozard.puppet.messages.Protocol.Location.getDefaultInstance();
      screen_ = com.google.protobuf.ByteString.EMPTY;
      ping_ = 0;
      cam_ = com.google.protobuf.ByteString.EMPTY;
      speech_ = "";
      voicecommand_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(1, screen_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getCmdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(4, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(5, getReqBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(6, getInfoBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(7, loc_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(8, ping_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(9, cam_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(10, getSpeechBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(11, getVoicecommandBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, screen_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCmdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getReqBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getInfoBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, loc_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, ping_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, cam_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getSpeechBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getVoicecommandBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sonymobile.wozard.puppet.messages.Protocol.Base parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Base parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Base parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Base parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Base parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Base parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Base parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Base parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Base parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Base parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sonymobile.wozard.puppet.messages.Protocol.Base prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.sonymobile.wozard.puppet.messages.Protocol.BaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sonymobile.wozard.puppet.messages.Protocol.internal_static_messages_Base_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sonymobile.wozard.puppet.messages.Protocol.internal_static_messages_Base_fieldAccessorTable;
      }

      // Construct using com.sonymobile.technology.ardemo.messages.Protocol.Base.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
          getLocFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmd_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (dataBuilder_ == null) {
          data_ = com.sonymobile.wozard.puppet.messages.Protocol.Data.getDefaultInstance();
        } else {
          dataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        req_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        info_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (locBuilder_ == null) {
          loc_ = com.sonymobile.wozard.puppet.messages.Protocol.Location.getDefaultInstance();
        } else {
          locBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        screen_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        ping_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        cam_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        speech_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        voicecommand_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sonymobile.wozard.puppet.messages.Protocol.Base.getDescriptor();
      }

      public com.sonymobile.wozard.puppet.messages.Protocol.Base getDefaultInstanceForType() {
        return com.sonymobile.wozard.puppet.messages.Protocol.Base.getDefaultInstance();
      }

      public com.sonymobile.wozard.puppet.messages.Protocol.Base build() {
        com.sonymobile.wozard.puppet.messages.Protocol.Base result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private com.sonymobile.wozard.puppet.messages.Protocol.Base buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.sonymobile.wozard.puppet.messages.Protocol.Base result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public com.sonymobile.wozard.puppet.messages.Protocol.Base buildPartial() {
        com.sonymobile.wozard.puppet.messages.Protocol.Base result = new com.sonymobile.wozard.puppet.messages.Protocol.Base(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.req_ = req_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.info_ = info_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (locBuilder_ == null) {
          result.loc_ = loc_;
        } else {
          result.loc_ = locBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.screen_ = screen_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.ping_ = ping_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.cam_ = cam_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.speech_ = speech_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.voicecommand_ = voicecommand_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sonymobile.wozard.puppet.messages.Protocol.Base) {
          return mergeFrom((com.sonymobile.wozard.puppet.messages.Protocol.Base)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sonymobile.wozard.puppet.messages.Protocol.Base other) {
        if (other == com.sonymobile.wozard.puppet.messages.Protocol.Base.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        if (other.hasReq()) {
          setReq(other.getReq());
        }
        if (other.hasInfo()) {
          setInfo(other.getInfo());
        }
        if (other.hasLoc()) {
          mergeLoc(other.getLoc());
        }
        if (other.hasScreen()) {
          setScreen(other.getScreen());
        }
        if (other.hasPing()) {
          setPing(other.getPing());
        }
        if (other.hasCam()) {
          setCam(other.getCam());
        }
        if (other.hasSpeech()) {
          setSpeech(other.getSpeech());
        }
        if (other.hasVoicecommand()) {
          setVoicecommand(other.getVoicecommand());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000020;
              screen_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              cmd_ = input.readBytes();
              break;
            }
            case 34: {
              com.sonymobile.wozard.puppet.messages.Protocol.Data.Builder subBuilder = com.sonymobile.wozard.puppet.messages.Protocol.Data.newBuilder();
              if (hasData()) {
                subBuilder.mergeFrom(getData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setData(subBuilder.buildPartial());
              break;
            }
            case 42: {
              bitField0_ |= 0x00000004;
              req_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000008;
              info_ = input.readBytes();
              break;
            }
            case 58: {
              com.sonymobile.wozard.puppet.messages.Protocol.Location.Builder subBuilder = com.sonymobile.wozard.puppet.messages.Protocol.Location.newBuilder();
              if (hasLoc()) {
                subBuilder.mergeFrom(getLoc());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoc(subBuilder.buildPartial());
              break;
            }
            case 64: {
              bitField0_ |= 0x00000040;
              ping_ = input.readUInt32();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000080;
              cam_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000100;
              speech_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000200;
              voicecommand_ = input.readBytes();
              break;
            }
          }
        }
      }

      private int bitField0_;

      // optional string cmd = 2;
      private java.lang.Object cmd_ = "";
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCmd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
        return this;
      }
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      void setCmd(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
      }

      // optional .messages.Data data = 4;
      private com.sonymobile.wozard.puppet.messages.Protocol.Data data_ = com.sonymobile.wozard.puppet.messages.Protocol.Data.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.sonymobile.wozard.puppet.messages.Protocol.Data, com.sonymobile.wozard.puppet.messages.Protocol.Data.Builder, com.sonymobile.wozard.puppet.messages.Protocol.DataOrBuilder> dataBuilder_;
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.sonymobile.wozard.puppet.messages.Protocol.Data getData() {
        if (dataBuilder_ == null) {
          return data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      public Builder setData(com.sonymobile.wozard.puppet.messages.Protocol.Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setData(
          com.sonymobile.wozard.puppet.messages.Protocol.Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeData(com.sonymobile.wozard.puppet.messages.Protocol.Data value) {
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              data_ != com.sonymobile.wozard.puppet.messages.Protocol.Data.getDefaultInstance()) {
            data_ =
              com.sonymobile.wozard.puppet.messages.Protocol.Data.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = com.sonymobile.wozard.puppet.messages.Protocol.Data.getDefaultInstance();
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.sonymobile.wozard.puppet.messages.Protocol.Data.Builder getDataBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      public com.sonymobile.wozard.puppet.messages.Protocol.DataOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.sonymobile.wozard.puppet.messages.Protocol.Data, com.sonymobile.wozard.puppet.messages.Protocol.Data.Builder, com.sonymobile.wozard.puppet.messages.Protocol.DataOrBuilder>
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.sonymobile.wozard.puppet.messages.Protocol.Data, com.sonymobile.wozard.puppet.messages.Protocol.Data.Builder, com.sonymobile.wozard.puppet.messages.Protocol.DataOrBuilder>(
                  data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      // optional string req = 5;
      private java.lang.Object req_ = "";
      public boolean hasReq() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getReq() {
        java.lang.Object ref = req_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          req_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setReq(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        req_ = value;
        onChanged();
        return this;
      }
      public Builder clearReq() {
        bitField0_ = (bitField0_ & ~0x00000004);
        req_ = getDefaultInstance().getReq();
        onChanged();
        return this;
      }
      void setReq(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        req_ = value;
        onChanged();
      }

      // optional string info = 6;
      private java.lang.Object info_ = "";
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getInfo() {
        java.lang.Object ref = info_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          info_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setInfo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        info_ = value;
        onChanged();
        return this;
      }
      public Builder clearInfo() {
        bitField0_ = (bitField0_ & ~0x00000008);
        info_ = getDefaultInstance().getInfo();
        onChanged();
        return this;
      }
      void setInfo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        info_ = value;
        onChanged();
      }

      // optional .messages.Location loc = 7;
      private com.sonymobile.wozard.puppet.messages.Protocol.Location loc_ = com.sonymobile.wozard.puppet.messages.Protocol.Location.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.sonymobile.wozard.puppet.messages.Protocol.Location, com.sonymobile.wozard.puppet.messages.Protocol.Location.Builder, com.sonymobile.wozard.puppet.messages.Protocol.LocationOrBuilder> locBuilder_;
      public boolean hasLoc() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.sonymobile.wozard.puppet.messages.Protocol.Location getLoc() {
        if (locBuilder_ == null) {
          return loc_;
        } else {
          return locBuilder_.getMessage();
        }
      }
      public Builder setLoc(com.sonymobile.wozard.puppet.messages.Protocol.Location value) {
        if (locBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loc_ = value;
          onChanged();
        } else {
          locBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setLoc(
          com.sonymobile.wozard.puppet.messages.Protocol.Location.Builder builderForValue) {
        if (locBuilder_ == null) {
          loc_ = builderForValue.build();
          onChanged();
        } else {
          locBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeLoc(com.sonymobile.wozard.puppet.messages.Protocol.Location value) {
        if (locBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              loc_ != com.sonymobile.wozard.puppet.messages.Protocol.Location.getDefaultInstance()) {
            loc_ =
              com.sonymobile.wozard.puppet.messages.Protocol.Location.newBuilder(loc_).mergeFrom(value).buildPartial();
          } else {
            loc_ = value;
          }
          onChanged();
        } else {
          locBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearLoc() {
        if (locBuilder_ == null) {
          loc_ = com.sonymobile.wozard.puppet.messages.Protocol.Location.getDefaultInstance();
          onChanged();
        } else {
          locBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public com.sonymobile.wozard.puppet.messages.Protocol.Location.Builder getLocBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getLocFieldBuilder().getBuilder();
      }
      public com.sonymobile.wozard.puppet.messages.Protocol.LocationOrBuilder getLocOrBuilder() {
        if (locBuilder_ != null) {
          return locBuilder_.getMessageOrBuilder();
        } else {
          return loc_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.sonymobile.wozard.puppet.messages.Protocol.Location, com.sonymobile.wozard.puppet.messages.Protocol.Location.Builder, com.sonymobile.wozard.puppet.messages.Protocol.LocationOrBuilder>
          getLocFieldBuilder() {
        if (locBuilder_ == null) {
          locBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.sonymobile.wozard.puppet.messages.Protocol.Location, com.sonymobile.wozard.puppet.messages.Protocol.Location.Builder, com.sonymobile.wozard.puppet.messages.Protocol.LocationOrBuilder>(
                  loc_,
                  getParentForChildren(),
                  isClean());
          loc_ = null;
        }
        return locBuilder_;
      }

      // optional bytes screen = 1;
      private com.google.protobuf.ByteString screen_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasScreen() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.google.protobuf.ByteString getScreen() {
        return screen_;
      }
      public Builder setScreen(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        screen_ = value;
        onChanged();
        return this;
      }
      public Builder clearScreen() {
        bitField0_ = (bitField0_ & ~0x00000020);
        screen_ = getDefaultInstance().getScreen();
        onChanged();
        return this;
      }

      // optional uint32 ping = 8;
      private int ping_ ;
      public boolean hasPing() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getPing() {
        return ping_;
      }
      public Builder setPing(int value) {
        bitField0_ |= 0x00000040;
        ping_ = value;
        onChanged();
        return this;
      }
      public Builder clearPing() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ping_ = 0;
        onChanged();
        return this;
      }

      // optional bytes cam = 9;
      private com.google.protobuf.ByteString cam_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasCam() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.google.protobuf.ByteString getCam() {
        return cam_;
      }
      public Builder setCam(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        cam_ = value;
        onChanged();
        return this;
      }
      public Builder clearCam() {
        bitField0_ = (bitField0_ & ~0x00000080);
        cam_ = getDefaultInstance().getCam();
        onChanged();
        return this;
      }

      // optional string speech = 10;
      private java.lang.Object speech_ = "";
      public boolean hasSpeech() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getSpeech() {
        java.lang.Object ref = speech_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          speech_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSpeech(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        speech_ = value;
        onChanged();
        return this;
      }
      public Builder clearSpeech() {
        bitField0_ = (bitField0_ & ~0x00000100);
        speech_ = getDefaultInstance().getSpeech();
        onChanged();
        return this;
      }
      void setSpeech(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        speech_ = value;
        onChanged();
      }
      // optional string voicecommand = 11;
      private java.lang.Object voicecommand_ = "";
      public boolean hasVoicecommand() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getVoicecommand() {
        java.lang.Object ref = voicecommand_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          voicecommand_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setVoicecommand(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        voicecommand_ = value;
        onChanged();
        return this;
      }
      public Builder clearVoicecommand() {
        bitField0_ = (bitField0_ & ~0x00000200);
        voicecommand_ = getDefaultInstance().getVoicecommand();
        onChanged();
        return this;
      }
      void setVoicecommand(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        voicecommand_ = value;
        onChanged();
      }
      // @@protoc_insertion_point(builder_scope:messages.Base)
    }

    static {
      defaultInstance = new Base(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.Base)
  }

  public interface DataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string name = 1;
    boolean hasName();
    String getName();

    // optional bytes data = 2;
    boolean hasData();
    com.google.protobuf.ByteString getData();
  }
  public static final class Data extends
      com.google.protobuf.GeneratedMessage
      implements DataOrBuilder {
    // Use Data.newBuilder() to construct.
    private Data(Builder builder) {
      super(builder);
    }
    private Data(boolean noInit) {}

    private static final Data defaultInstance;
    public static Data getDefaultInstance() {
      return defaultInstance;
    }

    public Data getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sonymobile.wozard.puppet.messages.Protocol.internal_static_messages_Data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sonymobile.wozard.puppet.messages.Protocol.internal_static_messages_Data_fieldAccessorTable;
    }

    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      name_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sonymobile.wozard.puppet.messages.Protocol.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sonymobile.wozard.puppet.messages.Protocol.Data prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.sonymobile.wozard.puppet.messages.Protocol.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sonymobile.wozard.puppet.messages.Protocol.internal_static_messages_Data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sonymobile.wozard.puppet.messages.Protocol.internal_static_messages_Data_fieldAccessorTable;
      }

      // Construct using com.sonymobile.technology.ardemo.messages.Protocol.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sonymobile.wozard.puppet.messages.Protocol.Data.getDescriptor();
      }

      public com.sonymobile.wozard.puppet.messages.Protocol.Data getDefaultInstanceForType() {
        return com.sonymobile.wozard.puppet.messages.Protocol.Data.getDefaultInstance();
      }

      public com.sonymobile.wozard.puppet.messages.Protocol.Data build() {
        com.sonymobile.wozard.puppet.messages.Protocol.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private com.sonymobile.wozard.puppet.messages.Protocol.Data buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.sonymobile.wozard.puppet.messages.Protocol.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public com.sonymobile.wozard.puppet.messages.Protocol.Data buildPartial() {
        com.sonymobile.wozard.puppet.messages.Protocol.Data result = new com.sonymobile.wozard.puppet.messages.Protocol.Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sonymobile.wozard.puppet.messages.Protocol.Data) {
          return mergeFrom((com.sonymobile.wozard.puppet.messages.Protocol.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sonymobile.wozard.puppet.messages.Protocol.Data other) {
        if (other == com.sonymobile.wozard.puppet.messages.Protocol.Data.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      }

      private int bitField0_;

      // optional string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }

      // optional bytes data = 2;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.Data)
    }

    static {
      defaultInstance = new Data(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.Data)
  }

  public interface LocationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional double longitude = 1;
    boolean hasLongitude();
    double getLongitude();

    // optional double latitude = 2;
    boolean hasLatitude();
    double getLatitude();
  }
  public static final class Location extends
      com.google.protobuf.GeneratedMessage
      implements LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(Builder builder) {
      super(builder);
    }
    private Location(boolean noInit) {}

    private static final Location defaultInstance;
    public static Location getDefaultInstance() {
      return defaultInstance;
    }

    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sonymobile.wozard.puppet.messages.Protocol.internal_static_messages_Location_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sonymobile.wozard.puppet.messages.Protocol.internal_static_messages_Location_fieldAccessorTable;
    }

    private int bitField0_;
    // optional double longitude = 1;
    public static final int LONGITUDE_FIELD_NUMBER = 1;
    private double longitude_;
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public double getLongitude() {
      return longitude_;
    }

    // optional double latitude = 2;
    public static final int LATITUDE_FIELD_NUMBER = 2;
    private double latitude_;
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getLatitude() {
      return latitude_;
    }

    private void initFields() {
      longitude_ = 0D;
      latitude_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, longitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, latitude_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, longitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, latitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sonymobile.wozard.puppet.messages.Protocol.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sonymobile.wozard.puppet.messages.Protocol.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sonymobile.wozard.puppet.messages.Protocol.Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.sonymobile.wozard.puppet.messages.Protocol.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sonymobile.wozard.puppet.messages.Protocol.internal_static_messages_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sonymobile.wozard.puppet.messages.Protocol.internal_static_messages_Location_fieldAccessorTable;
      }

      // Construct using com.sonymobile.technology.ardemo.messages.Protocol.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sonymobile.wozard.puppet.messages.Protocol.Location.getDescriptor();
      }

      public com.sonymobile.wozard.puppet.messages.Protocol.Location getDefaultInstanceForType() {
        return com.sonymobile.wozard.puppet.messages.Protocol.Location.getDefaultInstance();
      }

      public com.sonymobile.wozard.puppet.messages.Protocol.Location build() {
        com.sonymobile.wozard.puppet.messages.Protocol.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private com.sonymobile.wozard.puppet.messages.Protocol.Location buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.sonymobile.wozard.puppet.messages.Protocol.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public com.sonymobile.wozard.puppet.messages.Protocol.Location buildPartial() {
        com.sonymobile.wozard.puppet.messages.Protocol.Location result = new com.sonymobile.wozard.puppet.messages.Protocol.Location(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.latitude_ = latitude_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sonymobile.wozard.puppet.messages.Protocol.Location) {
          return mergeFrom((com.sonymobile.wozard.puppet.messages.Protocol.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sonymobile.wozard.puppet.messages.Protocol.Location other) {
        if (other == com.sonymobile.wozard.puppet.messages.Protocol.Location.getDefaultInstance()) return this;
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              longitude_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              latitude_ = input.readDouble();
              break;
            }
          }
        }
      }

      private int bitField0_;

      // optional double longitude = 1;
      private double longitude_ ;
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public double getLongitude() {
        return longitude_;
      }
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000001;
        longitude_ = value;
        onChanged();
        return this;
      }
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      // optional double latitude = 2;
      private double latitude_ ;
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getLatitude() {
        return latitude_;
      }
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000002;
        latitude_ = value;
        onChanged();
        return this;
      }
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.Location)
    }

    static {
      defaultInstance = new Location(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.Location)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Base_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_Base_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Data_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_Data_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protocol.proto\022\010messages\"\276\001\n\004Base\022\013\n\003c" +
      "md\030\002 \001(\t\022\034\n\004data\030\004 \001(\0132\016.messages.Data\022\013" +
      "\n\003req\030\005 \001(\t\022\014\n\004info\030\006 \001(\t\022\037\n\003loc\030\007 \001(\0132\022" +
      ".messages.Location\022\016\n\006screen\030\001 \001(\014\022\014\n\004pi" +
      "ng\030\010 \001(\r\022\013\n\003cam\030\t \001(\014\022\016\n\006speech\030\n \001(\t\022\024\n" +
      "\014voicecommand\030\013 \001(\t\"\"\n\004Data\022\014\n\004name\030\001 \001(" +
      "\t\022\014\n\004data\030\002 \001(\014\"/\n\010Location\022\021\n\tlongitude" +
      "\030\001 \001(\001\022\020\n\010latitude\030\002 \001(\001B+\n)com.sonymobi" +
      "le.technology.ardemo.messages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messages_Base_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messages_Base_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_Base_descriptor,
              new java.lang.String[] { "Cmd", "Data", "Req", "Info", "Loc", "Screen", "Ping", "Cam", "Speech", "Voicecommand", },
              com.sonymobile.wozard.puppet.messages.Protocol.Base.class,
              com.sonymobile.wozard.puppet.messages.Protocol.Base.Builder.class);
          internal_static_messages_Data_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_messages_Data_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_Data_descriptor,
              new java.lang.String[] { "Name", "Data", },
              com.sonymobile.wozard.puppet.messages.Protocol.Data.class,
              com.sonymobile.wozard.puppet.messages.Protocol.Data.Builder.class);
          internal_static_messages_Location_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_messages_Location_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_Location_descriptor,
              new java.lang.String[] { "Longitude", "Latitude", },
              com.sonymobile.wozard.puppet.messages.Protocol.Location.class,
              com.sonymobile.wozard.puppet.messages.Protocol.Location.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
